name = "logistic"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
assets = { directory = ".worker-next/assets", binding = "ASSETS" }
[observability.logs]
enabled = true
#[[kv_namespaces]]
#binding = "NEXT_CACHE_WORKERS_KV"
#id = "logistic"
