 main = ".open-next/worker.js"
  name = "vntransp"
  compatibility_date = "2025-03-25"
  compatibility_flags = ["nodejs_compat"]
  [assets]
  directory = ".open-next/assets"
  binding = "ASSETS"

  [vars]
  NEXT_PUBLIC_BASE_URL="https://vntranspbackend-production.up.railway.app/v1"

  [observability.logs]
  enabled = true