 main = ".open-next/worker.js"
  name = "logistic"
  compatibility_date = "2025-03-25"
  compatibility_flags = ["nodejs_compat"]
  [assets]
  directory = ".open-next/assets"
  binding = "ASSETS"

  [vars]
  NEXT_PUBLIC_BASE_URL=http://vntranspbackend-production.up.railway.app/v1